apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-custom-config
  namespace: home
data:
  custom.yaml: |
    # HTTP Configuration for reverse proxy
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.42.0.0/16
        - 10.43.0.0/16
    
    # Add your custom configurations below
    # Examples:
    # logger:
    #   default: info
    # recorder:
    #   purge_keep_days: 7
    notify:
      - name: email_notifier  # Optional: Gives it a friendly name (e.g., notify.email_notifier)
        platform: smtp
        sender: gorco@maine.rr.com  # Required: Your sending email address
        recipient: steve.gorey+home@gmail.com  # Required: Default recipient(s); can be a list like - email1@example.com / - email2@example.com
        server: smtp-relay.smtp-relay.svc.cluster.local
        port: 25
        encryption: none
        timeout: 15