apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: christmas-quiz
  namespace: quiz
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: quiz.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: christmas-quiz
            port:
              number: 80
