
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: it-tools-ingress
  namespace: tools
  annotations:
    # Allow traffic from both HTTP and HTTPS entry points
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  # Internal access via HTTP
  - host: it-tools.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: it-tools
            port:
              name: web
