apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghostfolio
  namespace: ghostfolio
spec:
  replicas: 0 #1
  selector:
    matchLabels:
      app: ghostfolio
  template:
    metadata:
      labels:
        app: ghostfolio
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: ghostfolio
          image: ghostfolio/ghostfolio:latest   # multi-arch, pulls arm64
          ports:
            - containerPort: 3333
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ghostfolio-secrets
                  key: DATABASE_URL
            - name: NODE_OPTIONS
              value: "--max-old-space-size=1536"
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: ghostfolio-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: ghostfolio-config
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ghostfolio-secrets
                  key: REDIS_PASSWORD
            - name: REDIS_DB
              valueFrom:
                configMapKeyRef:
                  name: ghostfolio-config
                  key: REDIS_DB
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ghostfolio-secrets
                  key: JWT_SECRET_KEY
            - name: ACCESS_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: ghostfolio-secrets
                  key: ACCESS_TOKEN_SALT
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: ghostfolio-config
                  key: NODE_ENV
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 2Gi
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 3333
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 3333
            initialDelaySeconds: 10
            periodSeconds: 10