# plaid-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plaid-ingress
  namespace: plaid
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: plaid.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: plaid-frontend-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: plaid-python-service
            port:
              number: 80